version: '3.9'
services:
  frontend:
    # コンテナ名
    container_name: susutto-frontend
    build:
      #docker buildコマンドを実行した場所(composeの場合は up等)
      context: ./
    # ホスト側ポート番号:コンテナ側ポート番号　
    ports:
      - '3000:3000'
    env_file:
      - .env.local
