version: '3'
services:
  api:
    # コンテナ名
    container_name: susutto-api
    build:
      #docker buildコマンドを実行した場所(composeの場合は up等)
      context: ./src
    # ホスト側ポート番号:コンテナ側ポート番号　
    ports:
      - '3000:3000'
    # 環境変数の設定
    environment:
      - DEBUG=app:*
    # コンテナ内のディレクトリをマウントする　仮想環境またはHOST環境に変更があった時に同じ状態にする
    volumes:
      - ./:/app
    #起動時のコンテナ内のカレントディレクトリ
    working_dir: /app
    env_file:
      - .env.local
